<?php

/**
 * @file
 * Provides an "add to cart" confirmation dialog, shown after the customer has
 * added a product his cart.
 */

/**
 * Implements hook_views_api().
 */
function commerce_add_to_cart_confirmation_views_api() {
  return array('api' => 3);
}

/**
 * Implements hook_entity_info_alter().
 *
 * Create new view mode for product display, commerce product.
 */
function commerce_add_to_cart_confirmation_entity_info_alter(&$entity_info) {
  $entity_info['commerce_product']['view modes']['add_to_cart_confirmation_view'] = array(
    'label' => t('Add to cart confirmation view'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_theme().
 */
function commerce_add_to_cart_confirmation_theme($existing, $type, $theme, $path) {
  return array(
    'commerce_add_to_cart_confirmation_message' => array(
      'variables' => array(
        'view' => '',
      ),
    ),
  );
}

/**
 * Theme function to render the confirmation message.
 */
function theme_commerce_add_to_cart_confirmation_message($variables) {
  $message = '<div class="added-product-title clearfix">' . t('Item successfully added to your cart') . '</div>';
  $message .= '<div class="button-wrapper">';
  $message .= '<div class="button checkout">' . l(t('Go to checkout'), 'cart') . '</div>';
  $message .= '<div class="button continue"><span class="commerce-add-to-cart-confirmation-close">' . t('Continue shopping') . '</span></div>';
  $message .= '</div>';
  $message .= $variables['view'];
  return '<div class="message-inner">' . $message . '<a class="commerce-add-to-cart-confirmation-close" href="#"><span class="element-invisible">' . t('Close') . '</span></a></div>';
}
